name: Keep Render Awake2

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes (UTC)
  workflow_dispatch:        # allows manual run from the Actions tab

permissions:
  contents: read

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Ping public + backend URLs
        run: |
          for url in \
            "https://www.emailyourrep.uk/" \
            "https://www.emailyourrep.uk/config" \
            "https://email-campaign-backend-ovtw.onrender.com/" \
            "https://email-campaign-backend-ovtw.onrender.com/config"
          do
            echo "Pinging $url"
            curl -A "keepalive-bot/1.0 (+https://github.com/${{ github.repository }})" -fsS -m 10 "$url" >/dev/null || true
          done
